uploads = []

[[generated]]
id = "OFR_heaiVgU28NyYUjab5"
uri = "file://artifacts/sen-market-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "cQEqAIs_EODDqPUG96XRV"
uri = "file://screenshots/home.jpg"
type = "image"
title = "Page d'accueil — Logo drapeau + nouvelles catégories"

[[outputs]]
id = "hMgnK2hXck71PAG5BHeQ4"
uri = "file://screenshots/boutiques.jpg"
type = "image"
title = "Page Boutiques & Couturiers"

[[outputs]]
id = "bQ08S0e2UdDAiwSjsj8os"
uri = "file://screenshots/publicite.jpg"
type = "image"
title = "Page Publicité"

[[outputs]]
id = "auNsK_VlI06Gg5nFIEH64"
uri = "file://senmarket-business-plan.pdf"
type = "pdf"
title = "SenMarket — Business Plan"

[[outputs]]
id = "dKPWwvhZ9CpTinpI2BA-j"
uri = "file://senmarket-previsionnel-revenus.pdf"
type = "pdf"
title = "SenMarket — Prévisionnel de Revenus"
