kind = "web"
previewPath = "/"
title = "Sen Market"
version = "1.0.0"
id = "artifacts/sen-market"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21293

[services.development]
run = "pnpm --filter @workspace/sen-market run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sen-market", "run", "build" ]
publicDir = "artifacts/sen-market/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21293"
BASE_PATH = "/"
